### ISSUE TITLE
How to user plugin in python or C# API?

### ISSUE THREAD

**Issue by zzeric** [dolphindb/DolphinDBPlugin#10]
for example access a mysql via Dolphindb Mysql plugin

**Comment by hzwale** [comment]
Configure preloadModules=plugins::mysql in the configuration file, modules or plug-ins that are automatically loaded upon system startup.
The API client can then use module functions such as 
`s.un (" conn = mysql::connect(' 127.0.0.1, 3306, 'root,' root, 'DolphinDB) ").`

**Comment by zzeric** [comment]
I can un?

> Configure preloadModules=plugins::mysql in the configuration file, modules or plug-ins that are automatically loaded upon system startup. The API client can then use module functions such as `s.un (" conn = mysql::connect(' 127.0.0.1, 3306, 'root,' root, 'DolphinDB) ").`

Do you mean session.run(" conn = mysql::connect(' 127.0.0.1, 3306, 'root,' root, 'DolphinDB) ")?

**Comment by hzwale** [comment]
yes
