### ISSUE TITLE
load plugin error

### ISSUE THREAD

**Issue by yuuuxt** [dolphindb/DolphinDBPlugin#13]
dolphindb: `dolphindb/dolphindb:v2.00.7`
plugin: downloaded from release200 branch

hbase plugin: successfully loaded (2nd time load notification: `The module [hbase] is already in use.`)

parquet plugin: `Couldn't load the dynamic library [/dolphindb/etc/libPluginParquet.so]: /dolphindb/etc/libPluginParquet.so: undefined symbol: _ZN6Domain8addTableERKSsS1_RSt6vectorI10ColumnDescSaIS3_EERS2_IiSaIiEE`

xgboost plugin: `Couldn't load the dynamic library [/dolphindb/etc/libPluginXgboost.so]: libgomp.so.1: cannot open shared object file: No such file or directory`

**Comment by hzwale** [comment]
I deployed a single node on centos7 and then loaded the plugin, and it worked。

```
loadPlugin("plugins/parquet/PluginParquet.txt");
(extractParquetSchema,loadParquet,loadParquetHdfs,loadParquetEx,parquetDS,saveParquet,saveParquetHdfs)
```

**Comment by yuuuxt** [comment]
could you provide more information, like what docker image you used? 

if "deploy" means you are not using docker, it's very likely you can reproduce what I met using docker.

**Comment by hzwale** [comment]
I didn't use docker. I try deploying dolphindb with docker
